services:
  - type: web
    name: flask-web
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn run:app --worker-class eventlet -w 1 -b 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
    scaling:
      minInstances: 1
